### ISSUE TITLE
JSON deserialization error due to maxJsonLength property being exceeded

### ISSUE THREAD

**Issue by thatChadM** [Shawson/Playnite-OculusLibrary#10]
[ready-at-dawn-lone-echo.zip](https://github.com/Shawson/Playnite-OculusLibrary/files/3992994/ready-at-dawn-lone-echo.zip)

2019-12-22 15:56:54.9366|DEBUG:Listing Oculus manifests
2019-12-22 15:56:55.2936|ERROR:Exception while processing manifest (C:\Program Files\Oculus\Software\Manifests\ready-at-dawn-lone-echo.json) : System.ArgumentException: Error during serialization or deserialization using the JSON JavaScriptSerializer. The length of the string exceeds the value set on the maxJsonLength property.
Parameter name: input
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type type, Int32 depthLimit)
   at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize[T](String input)
   at OculusLibrary.OculusLibraryPlugin.GetOculusAppManifests(String oculusBasePath) in d:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibraryPlugin.cs:line 153

The manifest should be attached.

**Comment by Shawson** [comment]
This might need this setting changed in the host application (Playnite) - presumably this is the largest json file you have amongst your oculus manifest files?

**Comment by Shawson** [comment]
I've opened a big on Playnite to request this be increased; https://github.com/JosefNemec/Playnite/issues/1606

**Comment by thatChadM** [comment]
Yep, it is the only one that had an error so it should be the largest one.

**Comment by Shawson** [comment]
Check out release 0.0.6 and let me know!

**Comment by thatChadM** [comment]
Finally logged back into the PC and confirmed that this is working in 0.0.6.  Thanks!
