### ISSUE TITLE
Failed to import anything with multiple libraries

### ISSUE THREAD

**Issue by thatChadM** [Shawson/Playnite-OculusLibrary#7]
The plugin is able to get one of two library locations, but due to the failure getting the location of the second (default) library the extension errors out without importing anything.

From log:
2019-12-21 00:24:13.8537|INFO:Executing Oculus GetGames
2019-12-21 00:24:13.8537|DEBUG:Trying to get Oculus base path (REG64)
2019-12-21 00:24:13.8537|DEBUG:Getting Oculus library locations from registry (Registry64)
2019-12-21 00:24:13.8537|DEBUG:Found library: D:\Oculus
2019-12-21 00:24:13.8537|ERROR:Exception opening registry keys: System.NullReferenceException: Object reference not set to an instance of an object.
   at OculusLibrary.OculusLibraryPlugin.GetOculusLibraryLocations(RegistryView platformView) in d:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibraryPlugin.cs:line 191
2019-12-21 00:24:13.8537|DEBUG:Trying to get Oculus base path (REG32)
2019-12-21 00:24:13.8537|DEBUG:Getting Oculus library locations from registry (Registry32)
2019-12-21 00:24:13.8537|DEBUG:Found library: D:\Oculus
2019-12-21 00:24:13.8537|ERROR:Exception opening registry keys: System.NullReferenceException: Object reference not set to an instance of an object.
   at OculusLibrary.OculusLibraryPlugin.GetOculusLibraryLocations(RegistryView platformView) in d:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibraryPlugin.cs:line 191
2019-12-21 00:24:13.8537|ERROR:Cannot ascertain Oculus library locations

This is the registry snippet that is being walked:

[HKEY_CURRENT_USER\Software\Oculus VR, LLC\Oculus\Libraries\83279bce-ed22-4ce9-a83a-937418c50fef]
"Path"="\\\\?\\Volume{7c0c84e2-1679-44a4-b92d-bfb4d15bf489}\\Oculus"
"OriginalPath"="D:\\Oculus"

[HKEY_CURRENT_USER\Software\Oculus VR, LLC\Oculus\Libraries\ee032afa-e311-4065-979c-60043c21899c]
"Path"="\\\\?\\Volume{2f6e92db-3ae4-40f7-93cc-4b51047c98c5}\\Program Files\\Oculus\\Software"

It appears that the registry key that is being looked for, OriginalPath, may not exist.  Instead, it seems that the guaranteed key is actually Path, which uses the volume identifier rather than a drive letter.  In the above registry snippet, my secondary library that lives on the D: drive has both Path and OriginalPath while the default library location that lives on the C: drive only has Path.

And this is the list of volume identifiers & corresponding drive letters gathered via powershell:
GWMI -namespace root\cimv2 -class win32_volume | FL -property DriveLetter, DeviceID

DriveLetter : D:
DeviceID    : \\?\Volume{7c0c84e2-1679-44a4-b92d-bfb4d15bf489}\

DriveLetter : C:
DeviceID    : \\?\Volume{2f6e92db-3ae4-40f7-93cc-4b51047c98c5}\

**Comment by Shawson** [comment]
Wow- thanks for such a detailed error report!  I'll take a look at this this weekend!

**Comment by Shawson** [comment]
Try the latest release  0.0.5

**Comment by thatChadM** [comment]
Ay, that worked!  Thanks for the quick update!

I did see one json error parsing a manifest file due to the string length, but I'll log that in a new issue.
